/*
 * blobs.h
 *
 * Model data linked into flash, generated by tools/gen_blobs.py.
 * acoustic and prosody go into the V5F image, wordvoc into the V3F
 * image. All const, so nothing costs SRAM. The pronunciation
 * dictionary is on the card, not here.
 */

#ifndef TTS_BLOBS_H
#define TTS_BLOBS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t  tts_blob_acoustic[];
extern const uint32_t tts_blob_acoustic_len;   /* 406524 */
extern const uint8_t  tts_blob_prosody[];
extern const uint32_t tts_blob_prosody_len;   /* 201120 */
extern const uint8_t  tts_blob_wordvoc[];
extern const uint32_t tts_blob_wordvoc_len;   /* 111947 */

#ifdef __cplusplus
}
#endif

#endif /* TTS_BLOBS_H */
