#ifndef PROSODY_WEIGHTS_INT8_META_H
#define PROSODY_WEIGHTS_INT8_META_H

/* Generated by quantize_v8_weights.py (v5 stochastic) */
#include <stdint.h>

#define PW8_WEIGHT_MAGIC 0x51355750u /* 'PW5Q' */
#define PW8_WEIGHT_TOTAL_BYTES 201120u

#define PW8_PHONE_COUNT 41u
#define PW8_STRESS_COUNT 4u
#define PW8_WORD_COUNT 14682u
#define PW8_PHONE_EMB_DIM 48u
#define PW8_STRESS_EMB_DIM 8u
#define PW8_WORD_EMB_DIM 8u
#define PW8_AUX_DIM 24u
#define PW8_INPUT_DIM 184u
#define PW8_HIDDEN_DIM 64u
#define PW8_GRU_GATE_DIM 192u
#define PW8_OUTPUT_DIM 3u
#define PW8_STOCHASTIC 1u

#define PW8_OFF_PHONE_EMB 16u
#define PW8_COUNT_PHONE_EMB 1968u
#define PW8_DTYPE_PHONE_EMB "int8"
#define PW8_OFF_STRESS_EMB 1984u
#define PW8_COUNT_STRESS_EMB 32u
#define PW8_DTYPE_STRESS_EMB "int8"
#define PW8_OFF_WORD_EMB 2016u
#define PW8_COUNT_WORD_EMB 117456u
#define PW8_DTYPE_WORD_EMB "int8"
#define PW8_OFF_PRE_W 119472u
#define PW8_COUNT_PRE_W 11776u
#define PW8_DTYPE_PRE_W "int8"
#define PW8_OFF_PRE_B 131248u
#define PW8_COUNT_PRE_B 64u
#define PW8_DTYPE_PRE_B "float32"
#define PW8_OFF_GRU_FW_IH_W 131504u
#define PW8_COUNT_GRU_FW_IH_W 12288u
#define PW8_DTYPE_GRU_FW_IH_W "int8"
#define PW8_OFF_GRU_FW_HH_W 143792u
#define PW8_COUNT_GRU_FW_HH_W 12288u
#define PW8_DTYPE_GRU_FW_HH_W "int8"
#define PW8_OFF_GRU_FW_IH_B 156080u
#define PW8_COUNT_GRU_FW_IH_B 192u
#define PW8_DTYPE_GRU_FW_IH_B "float32"
#define PW8_OFF_GRU_FW_HH_B 156848u
#define PW8_COUNT_GRU_FW_HH_B 192u
#define PW8_DTYPE_GRU_FW_HH_B "float32"
#define PW8_OFF_GRU_BW_IH_W 157616u
#define PW8_COUNT_GRU_BW_IH_W 12288u
#define PW8_DTYPE_GRU_BW_IH_W "int8"
#define PW8_OFF_GRU_BW_HH_W 169904u
#define PW8_COUNT_GRU_BW_HH_W 12288u
#define PW8_DTYPE_GRU_BW_HH_W "int8"
#define PW8_OFF_GRU_BW_IH_B 182192u
#define PW8_COUNT_GRU_BW_IH_B 192u
#define PW8_DTYPE_GRU_BW_IH_B "float32"
#define PW8_OFF_GRU_BW_HH_B 182960u
#define PW8_COUNT_GRU_BW_HH_B 192u
#define PW8_DTYPE_GRU_BW_HH_B "float32"
#define PW8_OFF_OUT_MU_W1 183728u
#define PW8_COUNT_OUT_MU_W1 8192u
#define PW8_DTYPE_OUT_MU_W1 "int8"
#define PW8_OFF_OUT_MU_B1 191920u
#define PW8_COUNT_OUT_MU_B1 64u
#define PW8_DTYPE_OUT_MU_B1 "float32"
#define PW8_OFF_OUT_MU_W2 192176u
#define PW8_COUNT_OUT_MU_W2 192u
#define PW8_DTYPE_OUT_MU_W2 "int8"
#define PW8_OFF_OUT_MU_B2 192368u
#define PW8_COUNT_OUT_MU_B2 3u
#define PW8_DTYPE_OUT_MU_B2 "float32"
#define PW8_OFF_OUT_LV_W1 192384u
#define PW8_COUNT_OUT_LV_W1 8192u
#define PW8_DTYPE_OUT_LV_W1 "int8"
#define PW8_OFF_OUT_LV_B1 200576u
#define PW8_COUNT_OUT_LV_B1 64u
#define PW8_DTYPE_OUT_LV_B1 "float32"
#define PW8_OFF_OUT_LV_W2 200832u
#define PW8_COUNT_OUT_LV_W2 192u
#define PW8_DTYPE_OUT_LV_W2 "int8"
#define PW8_OFF_OUT_LV_B2 201024u
#define PW8_COUNT_OUT_LV_B2 3u
#define PW8_DTYPE_OUT_LV_B2 "float32"
#define PW8_OFF_NORM_MEAN 201040u
#define PW8_COUNT_NORM_MEAN 3u
#define PW8_DTYPE_NORM_MEAN "float32"
#define PW8_OFF_NORM_STD 201056u
#define PW8_COUNT_NORM_STD 3u
#define PW8_DTYPE_NORM_STD "float32"
#define PW8_OFF_SCALES 201072u
#define PW8_COUNT_SCALES 12u
#define PW8_DTYPE_SCALES "float32"

/* Per-tensor scale factors */
#define PW8_SCALE_PHONE_EMB 0.03205135f  /* index 0 */
#define PW8_SCALE_STRESS_EMB 0.02180956f  /* index 1 */
#define PW8_SCALE_WORD_EMB 0.03459100f  /* index 2 */
#define PW8_SCALE_PRE_W 0.00476178f  /* index 3 */
#define PW8_SCALE_GRU_FW_IH_W 0.00769785f  /* index 4 */
#define PW8_SCALE_GRU_FW_HH_W 0.00691691f  /* index 5 */
#define PW8_SCALE_GRU_BW_IH_W 0.00694326f  /* index 6 */
#define PW8_SCALE_GRU_BW_HH_W 0.00747884f  /* index 7 */
#define PW8_SCALE_OUT_MU_W1 0.00918398f  /* index 8 */
#define PW8_SCALE_OUT_MU_W2 0.00091847f  /* index 9 */
#define PW8_SCALE_OUT_LV_W1 0.00555345f  /* index 10 */
#define PW8_SCALE_OUT_LV_W2 0.00094697f  /* index 11 */

#endif
